name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js 20
        uses: actions/setup-node@v5
        with:
          node-version: 20.x
          cache: yarn
      - name: Yarn Install
        run: yarn install
      - name: Build
        run: yarn build
      - name: Wait on tests
        uses: lewagon/wait-on-check-action@v1.4.0
        with:
          ref: master
          check-name: test
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
      - name: Clean ftp
        uses: StephanThierry/ftp-delete-action@v2.1
        with:
          host: ${{ secrets.FTP_SERVER }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          workingDir: /
          remoteFiles: "*.xml;facivon.ico;*.html;manifest.webmanifest;robots.txt;.ftp-deploy-sync-state.json"
          remoteDirectories: "assets"
      - name: Deploy on ftp
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: dist/
          server-dir: /
